### ISSUE TITLE
Assignment operator spacing error bug

### ISSUE THREAD

**Issue by adrake33** [duaraghav8/Solium#106]
In cases where a function returns multiple values, the error "Assignment operator must have exactly single space on both sides of it" is showing up even when the assignment operator only has single spaces on both sides of it.

Here is a simple example:

```
pragma solidity ^0.4.11;

contract Test {
    function testA() public constant returns (bytes20, bytes20) {
        return (0, 0);
    }

    function testB() {
        bytes20 varA;
        bytes20 varB;

        (varA, varB) = testA();
    }
}
```

**Comment by duaraghav8** [comment]
`v1.0.7` resolves this, apologies for the delay @adrake33 :)

**Comment by adrake33** [comment]
No worries. Thanks, @duaraghav8!

**Comment by antogh** [comment]
I have exactly the same problem reported in the 1st post 
I am using compiler soljson-v0.4.20+commit.3155dd80.js
Any help to silence this buggy warning? 
Thanks

**Comment by duaraghav8** [comment]
@antogh Most likely this is happening because your VSCode extension is using an older version of Solium, since this bug has already been resolved.
Most people have found https://github.com/beaugunderson/vscode-solidity-extended/issues/3 to be helpful.

```
cd ~/.vscode/extensions/beaugunderson.solidity-extended-3.0.2/
# update the version numbers in package.json, solium's latest is 1.1.5
npm i
# restart vscod
```

**Comment by antogh** [comment]
Thanks, @duaraghav8 
I will try your suggestion asap and possibly update the result here
