### ISSUE TITLE
missing location info (start, end) in several nodes of solparse

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#107]
after fixing this, create a test that takes all kinds of solidity code and checks all the nodes formed for the mandatory fields (`type`, `start` & `end`)

**Comment by duaraghav8** [comment]
@travs a crucial bug has just been fixed in solparse `v1.2.4`, please update if necessary.

**Comment by travs** [comment]
@duaraghav8 Excellent, thanks for the ping :)
