### ISSUE TITLE
Recent change resulted in many errors.

### ISSUE THREAD

**Issue by MicahZoltu** [duaraghav8/Solium#108]
It appears that a recent update to Solium (or one of its dependencies) has broken our build.
https://travis-ci.org/AugurProject/augur-core/builds/269321929

Small excerpt:
```
/app/src/Controller.sol:32:24: warning: '[object Object]' doesn't follow the mixedCase notation
/app/src/Controller.sol:36:27: warning: '[object Object]' doesn't follow the mixedCase notation
/app/src/Controller.sol:41:26: warning: '[object Object]' doesn't follow the mixedCase notation
```
Controller.sol:32: https://github.com/AugurProject/augur-core/blob/develop/src/Controller.sol#L32
```
    function initialize(Controller _controller) external onlyControllerCaller returns(bool) {
```

I don't see an update to Solium recently, but I do see an NPM update to solparse.  I assume that since Solium doesn't have locked in dependencies this resulted in a transitive dependency update that broke us, which also means we can't trivially rollback to a previous version.

Along with addressing this bug, I would like to also request that Solium switches to using fixed dependency versions rather than ranged dependencies so that a transitive update like this doesn't permanently break external builds until a fix can be found.

**Comment by Recmo** [comment]
This fixes it for me. I'll put in a PR.

```
diff --git a/lib/rules/mixedcase.js b/lib/rules/mixedcase.js
index 6923037..bfe6f53 100644
--- a/lib/rules/mixedcase.js
+++ b/lib/rules/mixedcase.js
@@ -91,8 +91,8 @@ module.exports = {
                                return;
                        }
 
-                       if (!mixedCaseRegEx.test (node.id)) {
-                               report (node, node.id);
+                       if (!mixedCaseRegEx.test (node.name)) {
+                               report (node, node.name);
                        }
                });
                
```

**Comment by duaraghav8** [comment]
@MicahZoltu the most convenient fix for now is to disable the `mixedcase` rule (the bug is strictly limited to this rule only).
I'm still not sure whether simply reverting back to an older solparse version would fix this problem because it seems like this bug existed from way before, only hadn't been discovered yet.

@Recmo Thanks! I've made a few changes to your branch. Your change removed the errors but wasn't the right one, since `node` in case of `InformalParameter` doesn't have a `name` field, so `node.name` would always be `undefined`.
Instead, you access `node.id.name` (`id` is actually an object and NOT a string, this object contains the `name` of the parameter passed. This name needs to be checked by the Regular expression).
Its not your fault, the master branch of solium is currently a mess -.-" But you did point out exactly where the bug was=)

**Comment by duaraghav8** [comment]
The breaking change has been fixed in a new solparse release. Please enable the `mixedcase` rule after updating solparse and let me know if the issue still persists.

**Comment by MicahZoltu** [comment]
It _appears_ the new solparse created some new problems for us.  I haven't fully debugged yet, but I'm getting a `comma-whitespace` not found and/or `warning: Incorrect Indentation: make sure only "        " is used as indentation for this line.` (it is).  We are currently running a fork of Solium to address some other bugs, so it is possible that we need to merge in recent changes to this repo in order for our fork to work with the new solparse?  I'll investigate further, but wanted to mention the above two in case someone knew of an obvious/easy answer.

**Comment by MicahZoltu** [comment]
I just tried switching to Solium off of npm.  I'm getting the following error despite https://github.com/duaraghav8/Solium/blob/master/config/solium.json#L39
```
Error: Rule comma-whitespace was not found
    at C:\Users\micah\Source\augur-core\node_modules\solium\lib\rules.js:128:11
    at Array.forEach (<anonymous>)
    at Object.load (C:\Users\micah\Source\augur-core\node_modules\solium\lib\rules.js:126:27)
    at EventEmitter.lint (C:\Users\micah\Source\augur-core\node_modules\solium\lib\solium.js:72:31)
    at lintString (C:\Users\micah\Source\augur-core\node_modules\solium\lib\cli.js:133:25)
    at lintFile (C:\Users\micah\Source\augur-core\node_modules\solium\lib\cli.js:166:9)
    at C:\Users\micah\Source\augur-core\node_modules\solium\lib\cli.js:187:11
    at Array.map (<anonymous>)
    at lint (C:\Users\micah\Source\augur-core\node_modules\solium\lib\cli.js:186:33)
    at Object.execute (C:\Users\micah\Source\augur-core\node_modules\solium\lib\cli.js:311:19)
No issues found.
```

**Comment by duaraghav8** [comment]
@MicahZoltu checking

**Comment by duaraghav8** [comment]
@MicahZoltu (while I'm looking at this prob) as of now ONLY update solparse, do not merge anything from duaraghav8/solium.

**Comment by MicahZoltu** [comment]
It appears the code we needed has been merged into Solium.  Is the issue that a release has not been cut for Solium since it was merged?  I believe one of the things we added was breaking out the whitespace checks into multiple checks, one of which was `comma-whitespace`.  Is Solium in a state right now where a release can't be cut?

**Comment by duaraghav8** [comment]
@MicahZoltu I think I know what went wrong. Can you tell me HOW you updated solparse in your system? Did you use `npm install -g solium`?

**Comment by MicahZoltu** [comment]
1. rm -rf node_modules
2. npm install solium 0.5.5
3. npx solium --dir src
