### ISSUE TITLE
"no-unused-vars" rule false positive in inherited contracts

### ISSUE THREAD

**Issue by elenadimitrova** [duaraghav8/Solium#11]
I get an `[ERROR] At line: x, column: y -> Variable 'someAddress' is declared but never used.` in the scenario below, in which the variable **is** used in contracts inheriting from the base but not in the base contract itself.

```
contract IMyContract {

  address public someAddress;

  function myFunction(address someVariable);
}

import 'IMyContract.sol';
contract MyContract is IMyContract {
  function someOtherFunction(address X)
  {
    someAddress = X;
  }
}

```

**Comment by duaraghav8** [comment]
I'm unable to reproduce the error with the code you've posted. In fact, when I comment out ```someAddress = X;```, then it gives me the var-not-used error (as expected), but when its not commented out, there is no error.

Could you tell me which version you're using? (```solium --version```)

**Comment by elenadimitrova** [comment]
solium@0.1.7

**Comment by elenadimitrova** [comment]
I just installed 0.1.8 and it is still throwing the error
```

---------------------------------------------------------------------------------------
FILE:	/contracts/IMyContract.sol
---------------------------------------------------------------------------------------

[WARNING] At line: 1, column: 0 -> Contract name 'IMyContract' doesn't follow the CamelCase notation

[ERROR] At line: 3, column: 2 -> Variable 'someAddress' is declared but never used.

```

**Comment by duaraghav8** [comment]
Ahh! When I test the whole code in a single file, it doesn't pose any errors.

You must've declared ```IMyContract``` in 1 file, and ```MyContract``` in another.
At a time, Solium lints only a single file, so **it is not informed whether you are using the variable in some other file or not**.

This needs fixing.

**Comment by duaraghav8** [comment]
Putting this link here for my own (future) reference
https://eslint.org/docs/rules/no-unused-vars#exported

**Comment by duaraghav8** [comment]
this issue no longer persists since solium does not check state variables for usage any more.
feel free to re-open in case you face this (or something similar).
