### ISSUE TITLE
Parser is very slow

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#114]
For large contracts (eg- https://github.com/oraclize/ethereum-api/blob/master/oraclizeAPI_0.4.sol), solparse is the bottleneck (took ~4 seconds for above file).
This has also been mentioned in #105 

Suggestions under consideration
1. Find ways to Make parsing faster (current status: using PEGjs to create parser out of AST spec)
2. Cache the AST & use it for next iteration if file hasn't been changed since last parse.
3. Switch to a new parser (tough one, since every rule gets changed due to API change) - try https://github.com/federicobond/solidity-parser-antlr
4. parse solidity files inside a project in parallel -> as AST is retrieved, send it for linting

More are welcome

**Comment by duaraghav8** [comment]
https://github.com/duaraghav8/solparse/commit/4836145cf3a70fdf66fee55e79314acadbf29379

**Comment by duaraghav8** [comment]
Solved in 1.1.6

**Comment by yxliang01** [comment]
https://github.com/duaraghav8/Ethlint/blob/b2a0c226f6d013524ab2b74f5d2116f71e4150eb/docs/known-issues.rst Didn't update the bottleneck part. Or, is the `solparse` still quite slow?

**Comment by duaraghav8** [comment]
@yxliang01 already updated in develop couple of days ago (should've done it ~4 months ago) - https://github.com/duaraghav8/Ethlint/blob/develop/docs/known-issues.rst#known-issues
