### ISSUE TITLE
indention warning on line starting with _

### ISSUE THREAD

**Issue by dissaranged** [duaraghav8/Solium#116]
a correctly indented line of form
_address.transfer(..)
throws an indention warning

the warning disappears when setting the statement in brackets or removing the dash

**Comment by duaraghav8** [comment]
@dissaranged thanks for reporting this. 2 of the rules - `indentation` & `whitespace` currently have a slightly flawed implementation. We'll soon be working on fixing these. Until then, you can choose to disable the rule if its flagging too many false positives for you.

**Comment by duaraghav8** [comment]
Fixed in `v1.0.3`
cc: @nuevoalex
