### ISSUE TITLE
Ignore specific lines if they're marked for it

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#118]
Devs should have the ability to mark a line of code with a comment to signal Solium that this line needs to be ignored while linting. No rules (core/plugin) must raise any issues if that line violates them.

**Comment by rudolfix** [comment]
That would also fix problems with weird solidity expressions that solparse does not support

**Comment by beaugunderson** [comment]
i started implementing this but am not sure i found the best way... my thought was to create an `ignore` rule that runs on comments and insert those into the context... then in `solium.lint` check the messages array for those with a line number that comes consecutively after one of the ignore messages and discard them

is there an easier/less hacky way?

**Comment by beaugunderson** [comment]
(there's no bounty for this but it is something the augur team has requested)

**Comment by duaraghav8** [comment]
I thought about this problem but haven't been able to find time to fix it (although its on priority)
There is (I believe) a cleaner approach:

- Modify solparse (parser used by solium) to parse and return a list of comments present in the given code. So for eg:
```
uint x = 100;
// hello world
/*
foo bar
*/
uint y = 200;
```

```
> ast = solparse.parse(sourceCode)
> console.log(ast.comments)

[ { type: 'Line',
    value: 'hello world',
    start: 13,
    end: 26,
    range: [ 13, 26 ] },
  { type: 'Block',
    value: '\nfoo bar\n',
    start: 27,
    end: 40,
    range: [ 27, 40 ] } ]
```

A convenience function inside solium allows us to get line & column info just by passing this node.

Using these comment nodes, we can easily apply ignore directives. Eslint already does this - https://github.com/eslint/eslint/blob/master/lib/util/apply-disable-directives.js#L31


^This seems like a cleaner approach but also more complicated. If you've had any luck in implementing your technique, do share. Else I'll take this up after merging the rule PRs.

**Comment by duaraghav8** [comment]
@beaugunderson Comment-based disabling is now available in beta - https://github.com/duaraghav8/Solium#configure-with-comments-beta
