### ISSUE TITLE
Fatal parse error on function types

### ISSUE THREAD

**Issue by rhomeister** [duaraghav8/Solium#120]
The following minimal example gives errors when executing solium, but `truffle compile` runs successfully:

```
pragma solidity ^0.4.15;

contract Bar {
    function(address) external returns (address) foo;
}
```

Result:

```
[FATAL ERROR] An error occurred while linting over [REDACTED]/Bar.sol: 
An error occured while parsing the source code: Expected ";", "{", comment, 
end of line, or whitespace but "f" found. Line: 4, Column: 50
```

Version
```
$ solium --version
1.0.0
```

**Comment by duaraghav8** [comment]
Thanks for reporting this @rhomeister 

**Below note is for my own reference**
- solparse Node `FunctionDeclaration` needs to accept Function name after modifiers too <-- Verify this first from solidity grammar & empirically
- push update for both v0 & v1 since not a breaking change

**Comment by chriseth** [comment]
Note that this is valid syntax, it is a declaration of a variable of function type. The derivation path in the grammar touches VariableDeclaration, then TypeName, then FunctionTypeName.

**Comment by duaraghav8** [comment]
v1.1.5 adds support for function data types, this issue is resolved.
