### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by kangarang** [duaraghav8/Solium#121]
If I set `camelcase` to `false`, I get a fatal error message when I execute the linter.

`$ solium --dir .` produces this error message:

> [FATAL ERROR] An error occurred while linting over /.../.../contracts/Contract.sol: A valid configuration object was not passed. Please see http://solium.readthedocs.io/en/latest/user-guide.html#configuring-the-linter for a valid config format.

Here's my `.soliumrc.json`

```json
{
  "extends": "solium:all",
  "rules": {
    "camelcase": false,
    "quotes": [
      "error",
      "double"
    ],
    "imports-on-top": "error",
    "indentation": [
      "error",
      4
    ],
    "whitespace": "error",
    "mixedcase": "warning",
    "semicolon-whitespace": "error",
    "operator-whitespace": "error",
    "deprecated-suicide": "warning",
    "pragma-on-top": "error",
    "no-unused-vars": "warning",
    "arg-overflow": [
      "warning",
      3
    ]
  }
}
```

**Comment by duaraghav8** [comment]
@kangarang Please set it to either "off" or 0 and try again
False is a value you use for v0 config files. Since you're using the v1 format, you can't user Boolean values

**Comment by kangarang** [comment]
@duaraghav8 ahh i see, thank you. yes, that works nicely.
