### ISSUE TITLE
Recognise Contract names in code

### ISSUE THREAD

**Issue by elenadimitrova** [duaraghav8/Solium#13]
Contract names should be CamelCase, and that's what Solium applies for the contract definition, however it appears to not recognise Contract names used outside of the `contract X` syntax, as for the following 
```
contract MyContract is IMyContract, IMyOtherContract {... }
```
throws a warning
```
 'IMyContract' doesn't follow the mixedCase notation
 'IMyOtherContract' doesn't follow the mixedCase notation
```

**Comment by duaraghav8** [comment]
solved in v0.1.9
