### ISSUE TITLE
Add option for custom config path

### ISSUE THREAD

**Issue by lukehedger** [duaraghav8/Solium#148]
Would be great to be able to specify a custom path for `.soliumrc.json` config files, like:

```
solium --dir contracts --config ./config/.soliumrc.json
```

Sorry if this already exists and I've missed it.

**Comment by duaraghav8** [comment]
This seems like a nice feature, since I've personally felt the need to put all my configs in 1 dir. Will work on it soon

**Comment by duaraghav8** [comment]
@lukehedger This option is now available in `v1.0.6`, thanks for suggestion!

**Comment by lukehedger** [comment]
Brilliant, thanks @duaraghav8! 🏎💨
