### ISSUE TITLE
Truffle integration

### ISSUE THREAD

**Issue by Mridhul40** [duaraghav8/Solium#153]
Sorry if this issue has already been raised or discussed before.

We use both truffle and solium for our project but have to run the linter separately before pushing.
@duaraghav8 any chance you can integrate solium into truffle so we **don't have to install or run anything seperetely?** The lint output can be given as part of truffle compile

cc @gnidan

**Comment by duaraghav8** [comment]
@Mridhul40 agreed, faced this problem myself.
@gnidan would you be interested in a solium integration? Since the linter comes as a js library, its easily pluggable. I could find time to submit a PR

**Comment by duaraghav8** [comment]
This issue is being worked on by @UtkarshGupta-CS

**Comment by duaraghav8** [comment]
https://github.com/UtkarshGupta-CS/truffle-security
