### ISSUE TITLE
Configurable indent size

### ISSUE THREAD

**Issue by satyrius** [duaraghav8/Solium#154]
Why is indention 4 spaces? Solidity code looks more like JavaScript and it's 2 spaces indention usually. Look at OpenZeppelin contracts, they use 2 spaces as well https://github.com/OpenZeppelin/zeppelin-solidity/tree/master/contracts. Why not make this configurable?

**Comment by satyrius** [comment]
Sorry. I found this setting right after posting the question.

```json
{
  "rules": {
    "indentation": [
      "error",
      2
    ],
  }
}
```

**Comment by duaraghav8** [comment]
was about to point the same! The latest version of solium is 1.0.9, so please use that and let me know in case you face any issues.
