### ISSUE TITLE
Single statement one-line control structures

### ISSUE THREAD

**Issue by 4gn3s** [duaraghav8/Solium#16]
If/else with one-line body can omit braces [according to the style guide](http://solidity.readthedocs.io/en/latest/style-guide.html#control-structures), but I get the following error:
```
Expected '{' after if clause
```
with the code:
```
modifier positive(uint256 amount) {
    if (amount <= 0)
       throw;
    _
}
```

**Comment by duaraghav8** [comment]
solved in v0.1.9
