### ISSUE TITLE
Security/no block members

### ISSUE THREAD

**Issue by LefterisJP** [duaraghav8/Solium#160]
I see that solium complains with an `error` for `block.timestamp` or for `now`. 

The maximum tolerance that the timestamp can have for seconds in the future [is 900](https://github.com/ethereum/wiki/blob/c02254611f218f43cbb07517ca8e5d00fd6d6d75/Block-Protocol-2.0.md). The protocol checks for this. So yes a very incentivized miner could manipulate this value but only within limits and for many cases where the contract just checks passage of time where seconds/minutes granularity is non-essential then it should be fine.

So I think that is an overkill. It should at least be downgraded to a warning.

**Comment by duaraghav8** [comment]
fixed in https://github.com/duaraghav8/Solium/releases/tag/v1.1.1

**Comment by LefterisJP** [comment]
thank you!
