### ISSUE TITLE
License Violation: Add copyright of Protofire to Solium

### ISSUE THREAD

**Issue by idrabenia** [duaraghav8/Solium#168]
Hi @duaraghav8 ,

You copy file `comment-directive-parser.js` from project https://github.com/protofire/solhint, file https://github.com/protofire/solhint/blob/master/lib/comment-directive-parser.js.

Please add copyright of Protofire according MIT license to the Solium.

Best Regards,
\- Ilya

**Comment by duaraghav8** [comment]
Hi @idrabenia,
Having the same file name doesn't qualify as copying. Plus I anyway didn't copy your code, I wrote my own after exploring how different tools (including solhint) solve the problem of comment directives. If that counts as copying, I'd be more than happy to give you credits, just point me to the right clause in the MIT license that defines this thing as copying.
Hope that clarifies

**Comment by idrabenia** [comment]
Ok, I will contact Github owners

**Comment by idrabenia** [comment]
We will write blog post on medium that you steel code instead of develop your own.

**Comment by idrabenia** [comment]
You may say all that you want - but community will see and compare.

Our company make all possible for this.
