### ISSUE TITLE
parse "emit" directive

### ISSUE THREAD

**Issue by ybabel** [duaraghav8/Solium#177]
When an event is triggered, now, the prefered syntax is to prefix it with an "emit".
But that makes the solium parser fails. It raises : 
> error    Syntax error: unexpected token (

**Comment by duaraghav8** [comment]
Thanks for reporting @ybabel 
This issue was also recently opened on Solium's solidity parsing engine (https://github.com/duaraghav8/solparse/issues/29). The fix will be available in the next version (3-5 days). I'm closing it here and tracking it in solparse's issues.
