### ISSUE TITLE
Release package on Snap Store

### ISSUE THREAD

**Issue by favadi** [duaraghav8/Solium#200]
I see the snapcraft.yaml already exists, should we enable uploading the snap package to Snap Store?

**Comment by favadi** [comment]
@elopio should we promote it to stable?

**Comment by elopio** [comment]
yeah, that would be cool. @duaraghav8 can you please move the v1.1.7 snap to candidate, so we test it a little? You can do this from dashboard.snapcraft.io, no need to install linux.

**Comment by duaraghav8** [comment]
@elopio I could only find the beta and edge channels on the release page, so I've released on both of them. Although I haven't finished reading the docs, I believe I will have to wait for some time before it allows me to release to candidate stage?

**Comment by elopio** [comment]
That's because we have a guardrail that says that the snap is in development. Updated here:
https://github.com/duaraghav8/Solium/pull/206

**Comment by duaraghav8** [comment]
@favadi @elopio I've just made the `candidate` release and will test it out on a linux machine. Please let me know in case you guys face any issues.

**Comment by duaraghav8** [comment]
Promoted to `stable`. Please re-open issue in case of any problem:)

**Comment by elopio** [comment]
@duaraghav8 I don't see the snap in stable, which I thing could be because you promoted other architectures and not amd64. I suppose you don't have ubuntu, nor want to get it, so you can add me as a contributor on dashboard.snapcraft.io and I can help you with the releases.

**Comment by duaraghav8** [comment]
@elopio My bad, must've missed that out. Did you receive a collaboration invite?

**Comment by elopio** [comment]
Yes, I am all set. What we are missing are annotated tags, so the `version: git` formats it nicely.
Using annoated tags is a good practice: https://stackoverflow.com/a/4971817/2665322
If you do this for 1.1.8, the release will be a lot easier.
