### ISSUE TITLE
Something is broken

### ISSUE THREAD

**Issue by Gargo** [duaraghav8/Solium#209]
I used truffle framework and it created migrations.sol
Contract is deploed successfully but Solium output:
`✖ [Fatal error] An error occurred while linting over <path>\contracts\Migrations.sol: Line number 23 invalid or out of bounds`.

**Comment by duaraghav8** [comment]
@Gargo Could you produce your contract code here (even if it was the migrations.sol that caused the error)?

**Comment by duaraghav8** [comment]
closing this, please re-open if you're facing the issue again with the code.
