### ISSUE TITLE
Solium output gcc format does not give rule name

### ISSUE THREAD

**Issue by KetkiT** [duaraghav8/Solium#229]
If we use command **solium -d . -R gcc** , the output produced does not contain rule name. 
However rule name is present for default format pretty . 
e.g   57:8    warning    Use emit statements for triggering events.    **emit**

This rule name is not retrieved from gcc format .
Can rule name be added in gcc format as well?

**Comment by duaraghav8** [comment]
@KetkiT I've fixed this, rule name will be available in the next release.
Thanks for reporting!

**Comment by KetkiT** [comment]
Thanks a lot. Can you please tell me when will be the next release ?

**Comment by duaraghav8** [comment]
Within this week, I'm in the process of reviewing a few PRs atm.

**Comment by KetkiT** [comment]
Thank you for quick reply ! All d best !

**Comment by duaraghav8** [comment]
1.1.8 is out

**Comment by KetkiT** [comment]
1.1.8 could not be seen in Releases

**Comment by KetkiT** [comment]
Thanks a lot.
