### ISSUE TITLE
Way to get the litteral emitted node ?

### ISSUE THREAD

**Issue by gomesalexandre** [duaraghav8/Solium#230]
Hi @duaraghav8 I'm currently working on the autofixes.

Unfortunately, I am not sure there is a way to get the litteral emitted node i.e the string representation of the code at that point ?
For example, I am trying to create a fixer function for functions order. 
Removing the node is an easy task, I can do it like this : 
```                            
fix(fixer) {
   return [
     fixer.remove(funcNode)
  ];
},
```

But do you provide an API to insert the original code somewhere else, without having to reconstruct it ?

Thanks !

**Comment by duaraghav8** [comment]
@gomesalexandre `context.getSourceCode().getText(funcNode)` gives the complete code of the provided node object. After that you could maybe use `fixer.insertTextAt()`

Please read the developer docs http://solium.readthedocs.io/en/latest/developer-guide.html#creating-a-core-rule

**Comment by gomesalexandre** [comment]
Thanks, exactly what I needed ! 
I read the docs but for some reason missed this
