### ISSUE TITLE
Solium failed for windows

### ISSUE THREAD

**Issue by KetkiT** [duaraghav8/Solium#234]
Hello , 
I am executing following command 

**c:\ProgramData\Gamma\data\tenants\04cf17a0ff69c6a52aabb70a45611fd3\checkouts\d44
afd7736617e248f5dbd07186cf9dc\src**>solium.cmd  -f  C:\ProgramData\Gamma\data\tenant
s\04cf17a0ff69c6a52aabb70a45611fd3\checkouts\d44afd7736617e248f5dbd07186cf9dc\sr
c\contracts\apps\AppProxyBase.sol -R  gcc

I am getting following error:

[Fatal error] An error occurred while linting over C:\ProgramData\Gamma\data\ten
ants\04cf17a0ff69c6a52aabb70a45611fd3\checkouts\d44afd7736617e248f5dbd07186cf9dc
\src\contracts\apps\AppProxyBase.sol: Line number 3 invalid or out of bounds.

Does it have any limit over length of the command ?

Reference : Git repo : https://github.com/aragon/aragonOS

**Comment by duaraghav8** [comment]
@KetkiT There are known bugs which result in unexpected behaviour in windows environment. We're working toward making Solium cross-platform but until then, I highly recommend you use Solium in a linux or OSX environment (perhaps use a linux docker container to avoid errors for now).

See #173 & #75
