### ISSUE TITLE
add test for pragma version statement

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#36]
`pragma solidity ^0.4.0`
`pragma solidity 0.4.0`

**Comment by tymat** [comment]
Additionally, this needs to be fixed:

```
[WARNING] At line: 1, column: 22 -> empty statement: There should be no character(s) before top-level declaration.
```

**Comment by duaraghav8** [comment]
@tymat could you paste your code which caused this warning?

**Comment by tymat** [comment]
@duaraghav8 

Any code that has pragma statement on the top.  

```
pragma solidity ^0.4.2;


contract MyContract {

    address public myAddress;

    function MyContract() {
        myAddress = address(this);
    }
}
```

**Comment by duaraghav8** [comment]
Oh my bad. I thought you were facing this problem due to some other reason. Thanks for bringing thisto my attention

**Comment by elenadimitrova** [comment]
Also adding that `pragma` statement should be at the top so therefore change `import`statement rule as well, which otherwise throws: 

```
[ERROR] At line: 3, column: 0 -> Import statement must be at the top of the file.
```

**Comment by duaraghav8** [comment]
@elenadimitrova @tymat **v0.2.0** solves the problems discussed above. But if something still doesn't work, please re-open
