### ISSUE TITLE
Implement exception for 'Use of empty block statement {}' rule for a payable fallback function

### ISSUE THREAD

**Issue by elenadimitrova** [duaraghav8/Solium#37]
Since Solidity 4 we are able to implement an empty payable fallback function

```
  function ()
  payable {}
```

Functionality defined in 
http://solidity.readthedocs.io/en/develop/frequently-asked-questions.html?highlight=payable#what-is-the-deal-with-function-inside-solidity-contracts-how-can-a-function-not-have-a-name

This however throws a warning in solium
`[WARNING] At line: x, column: y -> Use of empty block statement {}`

**Comment by duaraghav8** [comment]
solved in **v0.2.0**
