### ISSUE TITLE
Add support for reading input from stdin

### ISSUE THREAD

**Issue by federicobond** [duaraghav8/Solium#46]
This is useful for integrating with text editors and IDEs, as it allows linting from the latest buffer contents instead of the data on disk.

It could be implemented with an option named `--stdin`. For example:

```
cat MyContract.sol | solium --stdin
```

**Comment by duaraghav8** [comment]
@federicobond issues are closed once a new release is published, so I'll keep it for now.

**Comment by duaraghav8** [comment]
**v0.2.0**
