### ISSUE TITLE
Do not return error code > 0 if the only issues found are warnings

### ISSUE THREAD

**Issue by federicobond** [duaraghav8/Solium#47]

**Comment by MicahZoltu** [comment]
This is the _opposite_ of what I want (I actually came here to see if there was an option for marking warnings as errors).  If this is added, please be sure to make it configurable.

**Comment by duaraghav8** [comment]
@MicahZoltu next version of solium will allow you to configure whether to treat a rule as warning, error or turn it off altogether, similar to eslint.
eg- https://github.com/duaraghav8/Solium/blob/master/config/rulesets/solium-all.js

Plus you can pass options like `quotes: ["warning", "double"]`.

The cli will only return non-zero exit code if any errors exist.
Thanks @federicobond

**Comment by elenadimitrova** [comment]
@duaraghav8 is there a way to treat _all_ warnings as errors, rather than word them out individually?

**Comment by duaraghav8** [comment]
@elenadimitrova currently no. But I can see why this can be quite inconvenient. Do you have any ideas on how this configuration option should be presented to the end user, I can't think of a way which could be easy and also provide some flexibility (i.e. treat all as warnings or errors)

**Comment by elenadimitrova** [comment]
@duaraghav8 Perhaps we can go for a --strict option which does the switch from all warnings to errors but also honours the `rules` config that is additionally allowed to override behaviour in both strict and normal runs?

**Comment by duaraghav8** [comment]
moving discussion to #252
