### ISSUE TITLE
A better User Env

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#5]
The commandline displays simple text.
Maybe coloured text would be more helpful.

**Red**: Fatal Errors
**Blue**: Lint/Style errors

**Comment by duaraghav8** [comment]
Look into [color.js](https://github.com/marak/colors.js/)

**Comment by federicobond** [comment]
@duaraghav8 I think you can close this with the new output.

**Comment by duaraghav8** [comment]
Thanks @federicobond!
