### ISSUE TITLE
Allow uppercase acronyms in contract names

### ISSUE THREAD

**Issue by ulope** [duaraghav8/Solium#55]
The style guide doesn't specify whether all uppercase acronyms are acceptable in contract names (e.g. `IOUToken`). Personally I find nothing wrong with it. 

What do you think?

**Comment by duaraghav8** [comment]
hmm agreed, do you think the same should apply to names of Library, Structure and Event declarations too?

**Comment by ulope** [comment]
Yes I think that would make sense.
