### ISSUE TITLE
Block comments confuse indentation detection

### ISSUE THREAD

**Issue by ulope** [duaraghav8/Solium#65]
This example causes an (IMO) incorrect indentation warning
```
pragma solidity ^0.4.4;


contract Something {
    /* blah
     */
    function something(uint a, int b) returns (int c) {
        return a + b;
    }

    /* blah
     */
    function other(uint a, int b) returns (int c) {
        return a + b;
    }
}
```

```
In test.sol, line 12:
     */
^-- WARNING: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
```

Interestingly this only happens on the second (and all later) occurrences of a block comment not on the first.

**Comment by duaraghav8** [comment]
The indentation checker is doing its job alright. Because the ```*/``` has 1 extra space before it, the linter throws a warning because it doesn't see *exactly* 4 spaces (it sees 5 instead).

So I think we need to make an exception for the multi line comment.

**Comment by ulope** [comment]
But strangely the first occurrence is't recognized as a violation.

**Comment by duaraghav8** [comment]
closing this since the above script now gets through without any errors, opening up another todo item to write tests for ```indentation``` rule. Thanks for reporting!
