### ISSUE TITLE
Some thoughts on writing linter rules

### ISSUE THREAD

**Issue by federicobond** [duaraghav8/Solium#67]
I like the approach taken by `eslint`, where you return your visitor as an object with functions defined after each node type you want to visit, and also make heavy use of helper functions to refine the match.

See example here: https://github.com/eslint/eslint/blob/master/lib/rules/semi.js

@duaraghav8 perhaps you can take this into account in your refactor. Let me know what you think about it.

**Comment by duaraghav8** [comment]
https://github.com/duaraghav8/Solium/commit/e87567c352f1630102dc95c254138765ba90096d implements this
Thanks Fed!
