### ISSUE TITLE
indentation's not perfect yet

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Solium#7]
for eg- `ObjectExpression` or `StructDeclaration` doesn't get linted for indentation:

``` js
struct Foo ({
    hello: 'world'
});
```

same for `ArrayExpression` that span over multiple lines:

``` js
uint[] ages = [
    19,
    20
];
```

same for `CallExpression`

``` js
foo ({
    'hello': 'world'
});
```

something like this shouldn't bypass the wrath of solium:

``` js
foo (
    "hello", "world", "mofo"
);
```

1 arg per line, if you're spreading your function call over multiple line. Need to code logic for this too

``` js
if (true)
    hello();
```

Also read https://github.com/duaraghav8/Solium/pull/122

without block statement, indentation raises error saying no indent before "hello()" which shouldn't happen

**indentation is a bitch o.O**

**Comment by duaraghav8** [comment]
ensure that you check indentation thingy ONLY when start line & end line for param list is **not the same**

**Comment by elenadimitrova** [comment]
Worth changing the wording here to say "4 spaces" rather than 2, as this is what it's testing for.

https://github.com/duaraghav8/Solium/blob/master/config/solium.json#L99

As a nice-to-have would be to make this configurable as we here use 2-space indentation rather than 4, forcing us to switch off this rule altogether.

**Comment by Recmo** [comment]
Special case of the missing block statement, abstract functions also result in false positive:

```javascript
    function accessPolicy()
        public
        returns (IAccessPolicy);
```

**Comment by davesag** [comment]
another example

    other.call('transferFrom', myAddress, this, bond);

results in `WARNING: Function "undefined": in case of more than 3 arguments, drop each into its own line.`

but if I change it to

    other.call(
        'transferFrom',
        myAddress,
        this,
        bond
    );

I get `WARNING: Incorrect Indentation...`

A bit of a catch-22 here.

also while

    event Rejected(Claim claim, string reason);

is fine,

    event Rejected(
        Claim claim,
        string reason
    );

also trips an indentation error.

**Comment by duaraghav8** [comment]
@elenadimitrova configuration is now possible in v1
@Recmo @davesag please install the latest version (1.0.3) and let me know if the issues still persist for you.

**Comment by duaraghav8** [comment]
@elenadimitrova configuration is now possible in `v1`
@Recmo @davesag Your issues have been fixed in `v1.0.4` (latest). Thanks for reporting

**Comment by elenadimitrova** [comment]
Thanks @duaraghav8 ! Confirming this tests ok with custom 2-space rule.

**Comment by davesag** [comment]
all good. working great now.  thanks.
