### ISSUE TITLE
Add Atom package to README

### ISSUE THREAD

**Issue by travs** [duaraghav8/Solium#77]
Hey all, I've [made a simple package](https://atom.io/packages/linter-solium) for Atom that uses Solium as its core and gives some nice IDE-like features, like tooltips and lint underlining.

Just wanted to see if we should add it as an example in the readme, of Solium linting inside an editor.
Check it out and try it if you like; will be updating it with some more features in my spare time. 😄

**Comment by duaraghav8** [comment]
@travs this is great! Will add this to our documentation :)
