### ISSUE TITLE
Crashes when parsing an array as a return value

### ISSUE THREAD

**Issue by oed** [duaraghav8/Solium#85]
When parsing a contract that has a function which returns an array Solium chrashes.

To reproduce, lint this:
```
contract Test {
    function crash() returns (address[]) {
    }
}
```

**Comment by duaraghav8** [comment]
@oed are you sure that ```address[]``` is a valid usage?
I looked up in docs (http://solidity.readthedocs.io/en/develop/types.html), my interpretation is that it currently doesn't support dynamic arrays. Solc compiles the code but also produces a formal error that this is not supported.

The doc says:

```
Due to limitations of the EVM, it is not possible to return dynamic content from external function calls. The function f in contract C { function f() returns (uint[]) { ... } } will return something if called from web3.js, but not if called from Solidity.

The only workaround for now is to use large statically-sized arrays.
```

**Comment by oed** [comment]
@duaraghav8 I think it is supported, as long as you don't use the function with an internal call. External calls are fine.
http://solidity.readthedocs.io/en/latest/frequently-asked-questions.html?highlight=return%20array#can-you-return-an-array-or-a-string-from-a-solidity-function-call

`Returning variably-sized data as part of an external transaction or call is fine.`

**Comment by duaraghav8** [comment]
@oed I'm working on a fix for this :)

**Comment by duaraghav8** [comment]
@oed ```v0.5.1``` resolves this, please re-open the issue if you still face any trouble with this.
