### ISSUE TITLE
Multi-line if statements not possible?

### ISSUE THREAD

**Issue by oed** [duaraghav8/Solium#86]
I not sure if I'm missing something but when I do if statements with multiline checks I get errors. I looked through the solidity style guide but couldn't find any examples.

To replicate: 
```
contract TestLongIf {
    function longIf1() {
        if (someLongStatement1(param1, param2[key]) &&
            anotherLongThing[someKey] < VERY_IMPORTANT_CONSTANT) {
                throw;
        }
    }

    function longIf2() {
        if (someLongStatement1(param1, param2[key])
            && anotherLongThing[someKey] < VERY_IMPORTANT_CONSTANT) {
                throw;
        }
    }
}
```
Neither of the above works, but I don't know which one would be prefered.

**Comment by duaraghav8** [comment]
@oed allowed ```0.5.2``` onwards (will be released in some time)
```
function longIf1() {
        if (someLongStatement1(param1, param2[key]) &&
            anotherLongThing[someKey] < VERY_IMPORTANT_CONSTANT) {
                throw;
        }
    }
```

This style is allowed - **operator must be on the line where the left side of the expression ends and the right side of the expression should be on the next line (only a single line break allowed)**

**Comment by oed** [comment]
Awesome, thank you! :D
