### ISSUE TITLE
Add file change messages in watch mode, so that a vscode lint task can be configured.

### ISSUE THREAD

**Issue by ChihChengLiang** [duaraghav8/Solium#90]
Hi dear maintainers,
Thanks for all your hard works to this awesome project, it makes following good coding style easier.

<img width="511" alt="screen_shot_2017-07-25_at_12_14_57_am" src="https://user-images.githubusercontent.com/3391420/28533181-cdb0ade2-70ce-11e7-960c-8ccbc2159503.png">

It would be great to configure a vscode [lint task](https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks) for Solidity with Solium watch mode, so any style error would be instantly shows up in editor on file change.

To achieve that, Solium needs proper linting begin and end messages so that vscode problem matcher can capture the updated style errors.

Currently, the output of `solium --file Bounty.sol --watch --reporter=gcc` looks like:
```
*************************************************

Bounty.sol:11:0: warning: ContractStatement 'Bounty' must be preceded by a 2-line gap.

```
it starts with 49 '*'s and ends with nothing.

Ideally, messages with clear begin and end patterns ...
```
File change detected. Start linting.

Bounty.sol:11:0: warning: ContractStatement 'Bounty' must be preceded by a 2-line gap.
Linting complete. Watching for file changes.
```
... make linting task easier to be configured [like this](https://gist.github.com/ChihChengLiang/bd438b013d03de057adf22e64f8f36cd)
```
"beginsPattern": "^File change detected\\. Start linting\\.$",
"endsPattern": "^Linting complete\\. Watching for file changes\\.$"
```
So [here's my fork and source code change](https://github.com/duaraghav8/Solium/compare/master...ChihChengLiang:dev/add-proper-watching-mode-message?expand=1), if that does not break anything I can send a PR right away.

**Comment by duaraghav8** [comment]
@ChihChengLiang changes merged, this is extremely helpful, thanks! :D

**Comment by duaraghav8** [comment]
Solium `v1` makes this available.
`npm install -g solium@v1-beta`
http://solium.readthedocs.io/en/latest/
