### ISSUE TITLE
False upper case notation check on constant name

### ISSUE THREAD

**Issue by elenadimitrova** [duaraghav8/Solium#92]
When running solium against upper case constant names ending in numbers, the following warning is thrown:

```
uint128 constant public ALLOCATION_TEAM_MEMBER_2 = 80 * 10 ** 18;
  ^-- WARNING: Constant name 'ALLOCATION_TEAM_MEMBER2' doesn't follow the UPPER_CASE notation
```

**Comment by duaraghav8** [comment]
Solium `v1` resolves this issue.
`npm install -g solium@v1-beta`
http://solium.readthedocs.io/en/latest/
